### ISSUE TITLE
CoAP re-sending of LWM2M registration message

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#216] opened 2016-05-03 08:25 UTC
During the registration phase, CoAP re-sends the message. Normally this should not happen when acknowledge is received. In the **`Wireshark`** logging below is shown that the acknowledge is generated by the server  as expected. So I would not expect any re-send actions. I have also included DBG messages of the client, shown in _`italic`_.

Who is who:
aabb::1042:1aff:fea3:b01 =  client
aabb::30 = server
aabb::b5c9:feb:ee93:f959 = temporary address server

Send registration first time:
_`Listen port: 5683
Endpoint Name: Actuator - 12:42:1a:a3:0b:01
LWM2M server: coap://aabb::30:5683`_
_`[DBG ][ns_wrap]: ns_wrapper_socket_open(1)
waiting 5s before sending registration...
send_registration()`_
_`[DBG ][ns_wrap]: SOCKET_TX_DONE, 401 bytes sent`_

**`7	  6.555169	aabb::1042:1aff:fea3:b01    	aabb::30	CoAP	463	CON, MID:209, POST, /rd?ep=Actuator - 12:42:1a:a3:0b:01&et=test&lt=3600&b=U (text/plain)`**

**`8		6.571767	aabb::b5c9:feb:ee93:f959		aabb::1042:1aff:fea3:b01	CoAP	80	ACK, MID:209, 2.01 Created`**

_`[DBG ][ns_wrap]: SOCKET_DATA, sock=1, bytes=18`_
_`object_registered()`_

At this stage it seems the registration is finished, see client logging. Also the server has accepted the registration but on unfortunately a re-send action by NSDL CoAP is still performed:
 
**`9		10.632578	aabb::1042:1aff:fea3:b01	aabb::30	CoAP	463	CON, MID:209, POST, /rd?ep=Actuator - 12:42:1a:a3:0b:01&et=test&lt=3600&b=U (text/plain)`**
**`10		10.645575	aabb::b5c9:feb:ee93:f959		aabb::1042:1aff:fea3:b01	CoAP	80	ACK, MID:209, 2.01 Created`**

And again:
**`27	20.632362	aabb::1042:1aff:fea3:b01	aabb::30	CoAP	463	CON, MID:209, POST, /rd?ep=Actuator - 12:42:1a:a3:0b:01&et=test&lt=3600&b=U (text/plain)`**
**`28	20.641373	aabb::b5c9:feb:ee93:f959	aabb::1042:1aff:fea3:b01	CoAP	80	ACK, MID:209, 2.01 Created`**

After the re-sending of NSDL CoAP is finished, the client reports a resource not found error:
**`33	40.631592	aabb::1042:1aff:fea3:b01	aabb::30	CoAP	66	ACK, MID:209, 4.04 Not Found
`**

**Comment by yogpan01** [comment] 2016-05-03 08:32
Hi, This seems to be the issue that CoAP library in client is not able to identify whether the received Created Message is from the registration POST request so it is kicking up the CoAP re-transmission logic. Can you list your module versions where you are observing this ? Basically if you can put up your "yt ls" , we can check which specific versions are you experiencing this issue with.

**Comment by EduardPon** [comment] 2016-05-03 08:35
Here the requested info:

|_ mbed-client 1.9.2
| |_ mbed-client-c 2.3.3 yotta_modules\mbed-client-c
| | \_ nanostack-libservice 3.2.0 yotta_modules\nanostack-libservice

**Comment by ciarmcom** [comment] 2016-05-03 12:22
ARM Internal Ref: IOTCLT-728

**Comment by yogpan01** [comment] 2016-05-03 14:39
Hi, what is the mbed-client-mbed-os version that you are using ?

**Comment by EduardPon** [comment] 2016-05-04 05:05
Hello, 

My yotta mbed-os version:

openais-mbed-philips 0.1.0
|_ mbed-client 1.9.2
| |_ mbed-client-c 2.3.3 yotta_modules\mbed-client-c
| | \_ nanostack-libservice 3.2.0 yotta_modules\nanostack-libservice
| |_ mbed-trace 1.1.3 yotta_modules\mbed-trace
| |_ mbed-client-mbed-os 1.3.3 yotta_modules\mbed-client-mbed-os

**Comment by anttiylitokola** [comment] 2016-05-04 11:09
Hi.
We were able to reproduce this locally as well and the fix is now published in mbed-client version 1.9.4. I'll close this ticket now but feel free to open it again if you are still seeing duplicate messages.

**Closed by anttiylitokola** 2016-05-04 11:09 UTC
Labels: mirrored

**Comment by EduardPon** [comment] 2016-05-04 12:17
Hello,

The problem seems not to be fixed. I have verified your changes are part of my build (mbed-client version 1.9.4). At the moment we don't use a bootstrap server, so your changes won't have any effect.

**Comment by anttiylitokola** [comment] 2016-05-04 12:26
Hi,

My bad, I forgot to update registration part. There is now new PR opened, could you check is that working on your case as well?
https://github.com/ARMmbed/mbed-client/pull/222/files

**Comment by EduardPon** [comment] 2016-05-04 12:35
I build the change:
```
        _connection_handler->start_listening_for_data();
        if(_nsdl_interface->send_register_message((uint8_t*)event->_address->_address,event->_port, address_type)) {
            internal_event(STATE_REGISTER_RESOURCE_CREATED);
        } else {
```
But unfortunately this seems not to fix it. This part of code is executed (break point is entered).

**Comment by teetak01** [comment] 2016-05-04 13:53
We just published a fix to mbed-client-mbed-os library. Please update yotta modules to mbed-client-mbed-os 1.3.4.

**Comment by EduardPon** [comment] 2016-05-04 14:12
With the fixes ipv6 addr handling in mbed-client-mbed-os, the problem is fixed...thanks...
