### ISSUE TITLE
lwm2m - Device registers with a bad URL

### ISSUE THREAD

**Issue by Areontar** [ARMmbed/mbed-client#126] opened 2015-12-24 19:39 UTC
Hi, 

When creating the Device Object, the resource 11 is created for you and a resource instance is also created.  This is fine considering they are mandatory, but the registration message then contains 3/0/11/0 (last /0 being the resource instance) which I don't think is LWM2M compliant.  I believe Resource Instance is accessed using the payload (either TLV or JSON) but is not in the object Path.

This sadly this creates undesired behavior when connecting to certain servers as LWM2M does not have resource instance in the paths. I think they only exist as Array and cannot be in the URI (sent with unique ID on registration or discovery).

Thanks

**Comment by ciarmcom** [comment] 2015-12-24 21:13
ARM Internal Ref: IOTCLT-509

**Comment by teetak01** [comment] 2015-12-28 08:18
Thank you for reporting this. We will review this issue.

**Comment by Areontar** [comment] 2015-12-28 18:21
Thanks

**Comment by yogpan01** [comment] 2016-01-08 06:38
Hi, We would like to understand what is exact error occuring on the server side. Are you using Device Connector or is it some other LWM2M Server that you are testing against ? We would like to reproduce this error with your LWM2M server instance, if that would be possible,

**Comment by Areontar** [comment] 2016-01-11 19:45
Hi,
one of the server that can be used to reproduce the error is Leshan, It boils down to the fact that the resource Instance ID is in the Path (3/0/11/0), the last /0 make this an invalid lwm2m path.  I do understand the need to also offer pure CoAP (which would make this path legal), but because object 3 adds it automatically, which triggers the error.

Thanks

**Comment by yogpan01** [comment] 2016-01-12 08:37
Hi, yes I get the issue now when testing with Leshan server but as you already mentioned that because our mbed-client is also a generic client for other custom object /resources, it has been implemented in this way. I have now some idea as to how we can manage this issue so that mbed-client is compliant with both OMA objects as well as custom object. We will start working on this and let you keep updated with the ongoing fix.

**Comment by Areontar** [comment] 2016-01-12 22:34
awesome thanks!

**Comment by yogpan01** [comment] 2016-02-10 15:05
This is now fixed. Client is now sending only the device object instance as part of registration message.

**Closed by yogpan01** 2016-02-10 15:05 UTC
Labels: mirrored
